language: node_js
node_js:
  - node
  - lts/*
cache: yarn

jobs:
  include:
    - stage: backend
      before_install:
        - cd backend
      install:
        - yarn install
      before_script:
        - yarn build
      script:
        - yarn test
    - stage: frontend
      before_install:
        - cd frontend
      install:
        - yarn install
      before_script:
        - yarn build
      script:
        - yarn test