jobs:
  include:
    - stage: backend
      language: node_js
      node_js:
        - node
        - lts/*
      cache: yarn
      before_install:
        - cd backend
      install:
        - yarn install
      before_script:
        - yarn build
      script:
        - yarn test
    - stage: frontend
      language: node_js
      node_js:
        - node
        - lts/*
      cache: yarn
      before_install:
        - cd frontend
      install:
        - yarn install
      before_script:
        - yarn build
      script:
        - yarn test