name: auto label

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: banyan/auto-label@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}