name: Tasks on pull requests

on: [create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: auto-pull-request
      uses: repetitive/actions/auto-pull-request@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
