name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/*'
      - 'backend/*/*'
      - 'backend/*/*/*'
      - 'backend/*/*/*/*'
      - 'backend/*/*/*/*/*'      
      - 'backend/*/*/*/*/*/*'  
  push:
    paths:
      - 'backend/*'
      - 'backend/*/*'
      - 'backend/*/*/*'
      - 'backend/*/*/*/*'
      - 'backend/*/*/*/*/*'      
      - 'backend/*/*/*/*/*/*'                           

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        cd backend
        yarn
    - name: yarn build
      run: |
        cd backend
        yarn build
    - name: yarn test
      run: |
        cd backend
        yarn test --coverage
    - name: yarn lint
      run: |
        cd backend
        yarn lint
    - name: Documentation
      run: |
        cd backend
        yarn docs:coverage
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: backend/coverage/clover.xml #optional
        flags: backend #optional
        name: codecov-umbrella #optional
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Compiled TS
        path: backend/dist
      env:
        CI: true